name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # Ana branch'e her push yapıldığında çalışacak
  workflow_dispatch: # Manuel olarak çalıştırılabilir

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Install platform specific dependencies
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Build project
        run: npm run build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages with Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ZemaM-AC2dWX-z7rNnG
          CLOUDFLARE_ACCOUNT_ID: 865875349ebed4d48445e79e01c9ba0
        run: |
          # Direct upload to Cloudflare Pages
          wrangler pages deploy dist --project-name=canakyuz-portfolio --account-id=865875349ebed4d48445e79e01c9ba0 --commit-message="Deploy from GitHub Actions" --branch=main 