name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main # Ana branch'e her push yapıldığında çalışacak
  workflow_dispatch: # Manuel olarak çalıştırılabilir

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Install platform specific dependencies
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ZemaM-AC2dWX-z7rNnGDSWwCArVbg9UZIJGPgcCg
          CLOUDFLARE_ACCOUNT_ID: 865875349ebed4d48445e79e01c9ba0
        run: wrangler deploy 
